//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.18408
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;

public class CountTime
{
	float counter = 0;

	public float Counter{
		get{
			return counter;
		}
	}

	public CountTime(){}
	public CountTime(float time)
	{
		counter = time;
	}

	public bool Count(float to)
	{
		counter+=Time.deltaTime;
		return (counter>=to);
	}
		
	public void Reset()
	{
		Reset (0);
	}

	public void Reset(float val)
	{
		counter = val;
	}
}


